language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libantlr3c-dev antlr3 libcunit1-dev 
  - ./autogen.sh

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "e7J_OaeJYcXL4-WPO5s1gw"

addons:
  coverity_scan:
    project:
      name: "Gui13/belle-sip"
      description: "Your project description here"
    notification_email: guitreize@gmail.com
    build_command_prepend: ./configure
    build_command: make -j4
    branch_pattern: coverity_scan