language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libantlr3c-dev antlr3 libcunit1-dev 
  - ./autogen.sh

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "b/rirO3RzD5peVeP29fh6WCx9VY3dMKpSnn/f/R82+Wz8kUu6V0HGqAl0NaDXDNJ4Mvpq0FImednv/DsbHMwXQHg+kqOeTiyuMsJNdiwU2uaLYmN8hN9cU+cB6dKuKnqWEn3bdc8X6esYnPpdOnsQv4BYV3rHMApsx+ninbIYuI="

addons:
  coverity_scan:
    project:
      name: "Gui13/belle-sip"
      description: "Your project description here"
    notification_email: guitreize@gmail.com
    build_command_prepend: ./configure
    build_command: make -j4
    branch_pattern: coverity_scan